// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5x_AbWx83DsftK1EtEt6FKI0yRGHcYC0',
    appId: '1:516002987264:web:e6c9b3ba81308128a647e5',
    messagingSenderId: '516002987264',
    projectId: 'medicare-9d0de',
    authDomain: 'medicare-9d0de.firebaseapp.com',
    storageBucket: 'medicare-9d0de.firebasestorage.app',
    measurementId: 'G-MWXXR84E5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClsFNu7pj87NcjTmoCD2V-MIDsTzaYRws',
    appId: '1:516002987264:android:e7ba294f73a3694ca647e5',
    messagingSenderId: '516002987264',
    projectId: 'medicare-9d0de',
    storageBucket: 'medicare-9d0de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3cc-H3HWW4ETMGjFRMI3g39JHK8dy8iE',
    appId: '1:516002987264:ios:d70d810f1f2e3aefa647e5',
    messagingSenderId: '516002987264',
    projectId: 'medicare-9d0de',
    storageBucket: 'medicare-9d0de.firebasestorage.app',
    androidClientId: '516002987264-2fj8drsp4u95ialm95nhq10dosgs4prt.apps.googleusercontent.com',
    iosClientId: '516002987264-n65mrovogovtbo5mprs05rl15bm3k8l2.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3cc-H3HWW4ETMGjFRMI3g39JHK8dy8iE',
    appId: '1:516002987264:ios:d70d810f1f2e3aefa647e5',
    messagingSenderId: '516002987264',
    projectId: 'medicare-9d0de',
    storageBucket: 'medicare-9d0de.firebasestorage.app',
    androidClientId: '516002987264-2fj8drsp4u95ialm95nhq10dosgs4prt.apps.googleusercontent.com',
    iosClientId: '516002987264-n65mrovogovtbo5mprs05rl15bm3k8l2.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5x_AbWx83DsftK1EtEt6FKI0yRGHcYC0',
    appId: '1:516002987264:web:54659f27a71b6a49a647e5',
    messagingSenderId: '516002987264',
    projectId: 'medicare-9d0de',
    authDomain: 'medicare-9d0de.firebaseapp.com',
    storageBucket: 'medicare-9d0de.firebasestorage.app',
    measurementId: 'G-NDRWLEN4ZG',
  );

}