import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart' hide EmailAuthProvider; //
import 'package:firebase_ui_auth/firebase_ui_auth.dart'; //
import 'package:firebase_ui_oauth_google/firebase_ui_oauth_google.dart'; //
import 'firebase_options.dart'; // Generated by FlutterFire CLI

class profile extends StatefulWidget {
  const profile({super.key}); //constructor

  @override
  State<profile> createState() => _FormPageState();
}

class _FormPageState extends State<profile> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Input Form")),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          child: Column(
            children: [
              // sign out button
              ElevatedButton(
                onPressed: () async {
                  await FirebaseAuth.instance.signOut();
                },
                child: const Text('Log Out'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
